In [3]:
import pandas as pd
df = pd.read_excel("MEData_29-08-26.xlsx")

,WEEK,REGION,COUNTRY,ADMIN1,EVENT_TYPE,SUB_EVENT_TYPE,EVENTS,FATALITIES,POPULATION_EXPOSURE,DISORDER_TYPE,ID,CENTROID_LATITUDE,CENTROID_LONGITUDE
0,2016-02-06,Middle East,Bahrain,Capital,Battles,Armed clash,1,0,69821.0,Political violence,285,26.1927,50.5508
1,2026-02-28,Middle East,Bahrain,Capital,Explosions/Remote violence,Air/drone strike,9,0,126395.0,Political violence,285,26.1927,50.5508
2,2026-03-07,Middle East,Bahrain,Capital,Explosions/Remote violence,Air/drone strike,7,1,57503.0,Political violence,285,26.1927,50.5508
3,2026-03-14,Middle East,Bahrain,Capital,Explosions/Remote violence,Air/drone strike,1,0,22606.0,Political violence,285,26.1927,50.5508
4,2026-03-21,Middle East,Bahrain,Capital,Explosions/Remote violence,Air/drone strike,1,0,22606.0,Political violence,285,26.1927,50.5508

In [4]:
df.head()

,WEEK,REGION,COUNTRY,ADMIN1,EVENT_TYPE,SUB_EVENT_TYPE,EVENTS,FATALITIES,POPULATION_EXPOSURE,DISORDER_TYPE,ID,CENTROID_LATITUDE,CENTROID_LONGITUDE
0,2016-02-06,Middle East,Bahrain,Capital,Battles,Armed clash,1,0,69821.0,Political violence,285,26.1927,50.5508
1,2026-02-28,Middle East,Bahrain,Capital,Explosions/Remote violence,Air/drone strike,9,0,126395.0,Political violence,285,26.1927,50.5508
2,2026-03-07,Middle East,Bahrain,Capital,Explosions/Remote violence,Air/drone strike,7,1,57503.0,Political violence,285,26.1927,50.5508
3,2026-03-14,Middle East,Bahrain,Capital,Explosions/Remote violence,Air/drone strike,1,0,22606.0,Political violence,285,26.1927,50.5508
4,2026-03-21,Middle East,Bahrain,Capital,Explosions/Remote violence,Air/drone strike,1,0,22606.0,Political violence,285,26.1927,50.5508

In [10]:
df = df.sort_values(by='WEEK')
filtered_df = df[df['WEEK'] > '2026-03-07']

filtered_df.count()
filtered_df.to_csv("MEdata_08-03-26_to_29-08-26.csv", index=False)